<?php

namespace ContainerKKONnPz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Leadtech\Infrastructure\Controllers\User\Register' shared autowired service.
     *
     * @return \Leadtech\Infrastructure\Controllers\User\Register
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Leadtech/Infrastructure/Controllers/User/Register.php';

        $container->services['Leadtech\\Infrastructure\\Controllers\\User\\Register'] = $instance = new \Leadtech\Infrastructure\Controllers\User\Register();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'form.factory' => '?',
            'parameter_bag' => '?',
        ]))->withContext('Leadtech\\Infrastructure\\Controllers\\User\\Register', $container));

        return $instance;
    }
}
