<?php

namespace ContainerKKONnPz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterUseCaseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Leadtech\Application\User\RegisterUseCase' shared autowired service.
     *
     * @return \Leadtech\Application\User\RegisterUseCase
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Leadtech/Application/User/RegisterUseCase.php';
        include_once \dirname(__DIR__, 4).'/src/Leadtech/Domain/Interfaces/User/UserRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Leadtech/Infrastructure/Repository/User/MysqlRepository/UserRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Leadtech/Domain/Interfaces/EventBusInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Leadtech/Infrastructure/EventBus/MysqlEventBus.php';

        return $container->privates['Leadtech\\Application\\User\\RegisterUseCase'] = new \Leadtech\Application\User\RegisterUseCase(new \Leadtech\Infrastructure\Repository\User\MysqlRepository\UserRepository(), throw new RuntimeException('Cannot autowire service "Leadtech\\Infrastructure\\EventBus\\MysqlEventBus": argument "$entityManager" of method "__construct()" references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
