<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDvz89GO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDvz89GO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDvz89GO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDvz89GO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDvz89GO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dvz89GO',
    'container.build_id' => '5dc78aa7',
    'container.build_time' => 1721068409,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDvz89GO');
