<?php

namespace ContainerKKONnPz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PZOE5gkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PZOE5gk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PZOE5gk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'registerUseCase' => ['privates', 'Leadtech\\Application\\User\\RegisterUseCase', 'getRegisterUseCaseService', true],
        ], [
            'registerUseCase' => 'Leadtech\\Application\\User\\RegisterUseCase',
        ]);
    }
}
